regl-project/regl

lib/buffer.js

The error message generated by subdata() is
```
invalid buffer subdata call, buffer is too small
```
This is too concise and cryptic, and not really useful when you are debugging. I made this message more descriptive, so that it looks more like
```
invalid buffer subdata call, buffer is too small.  Can't write data of size 1452 starting from offset 0 to a buffer of size 1442
```

Clarified the error message of subData

---

example/camera.js

In the `camera.js` example, a function that draws a bunny was mistakenly named `cube()`. Renamed this function to `drawBunny()`

Rename `cube()` to `drawBunny` in `camera.js`

---

lib/core.js
lib/framebuffer.js
lib/texture.js
lib/util/check.js
lib/util/is-array-like.js

This PR fixes a bunch of validation issues caused by changes to the texture API and uniform validation introduced in 0.8.0.  It should triage the following issues:
* https://github.com/mikolalysenko/regl/issues/28
* https://github.com/mikolalysenko/regl/issues/30
There are 3 things that it adds:
1. It fixes a typo with float texture construction
2. Instead of checking if an input is an array using `Array.isArray`, for flat arrays we now use the new function `isArrayLike()` that also tests if the array is a typed array.  This is now applied to uniforms and in several other places in the validation logic.
3. There were a few bugs in the frame buffer logic caused by changes in the textures that were solved.

Validation fixes

---

regl.js

This PR fixes a small logical error in the RAF handler.  Previously it was resetting all WebGL state which isn't necessary.  Also, the RAF loop now calls `gl.flush()` once all commands have completed.

Use poll() instead of refresh() in raf handler

---

API.md
CHANGES.md
example/cloth.js
regl.js

This PR removes the deltaTime context variable.  deltaTime encourages error prone code like using a variable time step for simulations or games.

Remove deltaTime

---

lib/core.js

Found this when investigating the test coverage results.  The problem was caused by some legacy cruft not getting correctly updated during the big refactor in 0.7.0.

Fixed bug with draw properties incorrectly lowering in batch mode

---

lib/buffer.js
lib/elements.js
regl.js

This PR implements separate resource tracking for element buffers.  This solves #40 and is necessary for the last test cases in #41 to pass.

Track and destroy element buffers separately

---

API.md
CHANGES.md
lib/renderbuffer.js
test/renderbuffer.js

This PR refactors the render buffer resource type, paving the way for improvements to the frame buffer constructor.  It also adds a `resize()` method to renderbuffers so they can be quickly resized in place.

Refactor renderbuffers

---

example/audio.js
example/batch.js
example/bunny.js
example/camera.js
example/cloth.js
example/cube.js
example/dds.js
example/dynamic.js
example/envmap.js
example/feedback.js
example/geomorph.js
example/life.js
example/lighting.js
example/microphone.js
example/minecraft.js
example/mipmap.js
example/particles.js
example/pong.js
example/stats.js
example/text.js
example/theta360.js
example/tile.js
example/video.js

Currently, you have to call `regl.updateTimer` for every frame. Otherwise, you will keep on creating and starting queries without ever finishing them, and this causes the performance to get worse and worse. So I added `regl.updateTimer()` to the beginning of every frame in the examples.

Add `regl.updateTimer()` call to examples.

---

example/shadow_map.js
package.json

Added an example that shows how to implement shadow mapping. This demonstrates the framebuffer feature.

Shadow map example

---

example/deferred_shading.js

Remove `updateTimer()` from `deferred_shading.js`, since it has been removed from the API.

Remove `updateTimer()` from `deferred_shading.js`

---

CHANGES.md

Remove "Shadow mapping" from list of examples. Since it has been implemented now.
Add two new example items.

Remove "Shadow mapping" from list of examples. Add more example items

---

API.md

Fix the incomplete table "Color Type" for the Framebuffers documentation. This solves issues #57

Fix the incomplete table "Color Type" for the Framebuffers documentation.

---

lib/framebuffer.js
test/framebuffer-parse.js

This PR adds validation logic that prevents us from creating an FBO with render targets that have differing bitplanes. This resolves issue #64.

Added Framebuffer bit planes validation

---

API.md

Fix gl.LINES quote typo.
Fixed from
gl.LINES`
to 
`gl.LINES`

Fix gl.LINES quote typo.

---

example/instance-mesh.js
example/instance-triangle.js

This PR adds two examples that demonstrates the instancing feature of regl.
One example draws a bunch of triangles with instancing:
The other example draws a bunch of meshes with instancing:
This PR partly solves issue #69

Added Instancing examples

---

lib/core.js

In `lib/core.js` there was a missing `check.optional` for `assert` in `emitCount()`. This meant that for some programs built for the gallery(and all programs built for production), you would only get the error
```
stats.js.html:62 Uncaught TypeError: a.assert is not a function
```
And white screen. This PR fixes that.

`lib/core.js`: Insert missing `check.optional` in emitCount().

---

example/instance-mesh.js
example/instance-triangle.js

Fix so that the instance examples `example/instance-mesh.js` and `example/instance-triangle.js`
use the new extension loading mechanism in the `regl` constructor.

Fix the instance examples

---

API.md

`rgb565` was mistakenly written as `rgb5` in some places in API.md. Fixed that.

Fix `rgb565` => `rgb5`

---

API.md

'atc' was mistakenly written 'arc' in some places in API.md. Fixed that.

arc => atc

---

lib/texture.js

Change from the misspelling 'rgb arc' to 'rgb atc'.

lib/texture.js: fix 'rgb arc' => 'rgb atc'

---

API.md

'depth stencil' is also a supported renderbuffer format, but it was not mentioned in the API. Added.

Added 'depth stencil' format to renderbuffer docs

---

.npmignore

Added a few more directories to the npmignore list.  We shouldn't be publishing the code coverage results, comparison scripts or test images.

Update npmignore, should not publish code coverage results

---

API.md

All the possible values of 'mipmap' are now documented.
This resolves issue #47

API.md: Document option 'mipmap' of `regl.texture`

---

bench/bench.js
bench/cube-webgl.js
bench/list.js
www/bench.html

The `webgl-cube` benchmark is now more efficient, meaning that the comparison between `webgl-cube` and `cube`(the same example, but implemented in regl) will be more fair.
Also, update the benchmark webpage.

Optimize `webgl-cube` benchmark

---

test/batch-attributes.js

Remove TODO for instancing tests, since was solved in PR #81

 test/batch-attributes.js: remove TODO for instancing tests.

---

test/framebuffer-depth-stencil.js
test/framebuffer-mrt.js
test/framebuffer-parse.js
test/renderbuffer.js
test/texture2d.js
test/textureCube.js

Not all the tests were loading all the optional extensions they were using. Fixed that.

Load optional extensions in test cases

---

API.md

* Remove LUMINANCE, ALPHA, LUMINANCE_ALPHA, RGB entries. 
* Add missing SRGB entry. 
* Add links to extensions for color formats that need it.

API.md: Update framebuffer color format table.

---

lib/framebuffer.js
lib/texture.js
test/framebuffer-parse.js
test/framebuffer-resize.js
test/texture2d.js

This PR adds more test cases for framebuffers, and fixes several edge cases in framebuffers.
* Test cases for `colorFormat`, `colorType` and `colorCount` are added, thus resolving issue #61.
* We remove support for color attachments with the formats `GL_LUMINANCE`. `GL_ALPHA`, `GL_LUMINANCE_ALPHA`, since they are not renderable. Supporting them in the first place was a mistake, since they did not work. Also `GL_RGB` is removed, due to spotty browser support(did not work in Firefox).
* Add test cases for `framebuffer.resize()` for MRT.
* Before this PR, you could not create an FBO like this:
```javascript
const fbo = regl.framebuffer({
colorType: 'float',
colorFormat: 'rgba',
colorCount: 3,
depth: true
})
```
because the three color attachments would default to width and height of 0, and …

Improve framebuffer test cases

---

example/point-light-shadow.js

Add an example that shows how to render point-light shadows in `regl`.

Add Point light shadow example

---

API.md
lib/read.js
regl.js
test/framebuffer-parse.js
test/read.js

With this PR, you can `regl.read()` pixels from the currently bound
FBO, and
* if the fbo is of type 'float', you get a Float32Array.
* if the fbo is of type 'uint8', you get a Uint8Array.
For all other types, an exception is thrown. And reading from renderbuffers is not allowed
This PR resolves issue #136

Implement `regl.read` for framebuffers of type `uint8` and `float`

---

bench/bench.js

bench/bench.js: Fix so that we do not run benchmark 'cube-threejs' in headless.

Do not run 'cube-threejs' in headless

---

API.md

API.md: Remove unsupported color formats for cubic FBOs

API.md: Remove unsupported color formats for cubic FBOs

---

CHANGES.md
example/blur.js
example/cube-fbo.js
example/deferred_shading.js
example/graph.js
example/life.js
example/point-light-shadow.js
example/shadow_map.js
lib/core.js

Support directly passing framebuffer objects into texture uniforms.  This makes using framebuffer objects in ping-pong a bit less verbose.  The `.color` array can still be accessed for multiple render targets.

Framebuffer uniform

---

package.json
test/util/browser.js

This PR removes the tap-browser-color dependency and replaces it with a more efficient browser update scheme.  Now the browser tests complete in about the same amount of time as the headless version.
Fixes #177

Browser test perf

---

test/stencil.js

This improves the cases for the stencil buffer:
* Test for all possible values of `func.cmp`
* Test for dynamic properties in nested state. As part of solving issue #208

Improve stencil test cases

---

.remarkrc
API.md
CHANGES.md
DEVELOPING.md
README.md
compare/cube/threejs_cube.html
compare/cube/webgl_cube.html
package.json

Went down a rabbit hole and implemented a linter for all the docs. It currently doesn't run on CI due to an incompatibility with node 0.10, but you can still use it locally.
Also the table for the API docs are now auto generated.

Lint all markdown files

---

lib/core.js
test/blend.js
test/stencil.js

This PR:
* Improves the blend test cases by ensuring that all possible values of `blend.func.` work
* Solves issue #215, and add test cases for it.
* Partially solves issue #208, by adding testing for dynamic nested properties for blend.

Blend test cases improvements

---

API.md

Fix link to gl.sampleCoverage in API.md

API.md: Fix gl.sampleCoverage link

---

lib/texture.js

Made the error message "inconsistent array length for texture" more helpful.

Better error message for inconsistent array length for texture.

---

bin/check-dependecies.js
package.json

Currently it check all `js` files except patterns in `.gitignore` and ignore list of `standard`
Refer to https://github.com/mikolalysenko/regl/pull/243

Add simple script to check missing npm dependencies

---

API.md
CHANGES.md
example/shadow-volume.js
example/stencil-transition.js
lib/core.js
regl.js
test/framebuffer-depth-stencil.js
test/stencil.js

* Changes `pass` to `zpass`
* Can now specify `op` to simultaneously set `opFront` and `opBack`

Stencil buffer interface improvements

---

lib/core.js

Fix so that the 'instancing' extension is not only injected for 'draw'
calls, but also for the other types.

lib/core.js: fix instancing extension injection

---

API.md

Write better documentation for the 'channels' option of `regl.texture`
This resolves issue #275.

API.md: Document texture 'channels' option

---

API.md
lib/texture.js
test/texture2d.js

This PR allows you to retrieve the information 'format', 'type, 'mag', 'min', 'wrapS' , 'wrapT', after the texture creation. 
These properties can be accessed after texture creation like this:
```javascript
var t = regl.texture({
shape: [16, 16],
min: 'nearest mipmap linear',
mag: 'linear',
wrapS: 'mirror',
wrapT: 'repeat',
format: 'rgb',
type: 'uint8'
})
console.log('f: ', t.min, t.mag, t.wrapS, t.wrapT, t.format, t.type)
```
this PR resolves issue #273.

Add more texture properties

---

API.md
lib/renderbuffer.js
lib/texture.js
test/renderbuffer.js
test/textureCube.js

You can now query these properties of a cube map after creation: width, height, format, type, mag, min, wrapS, wrapT. Like this:
```javascript
var c = regl.cube({
width: 2,
height: 2
})
console.log('cube: ', c.width, c.height, c.format, c.type, c.mag, c.min, c.wrapS, c.wrapT)
```
you can now also query the 'format' of a renderbuffer after creation:
```javascript
var r = regl.renderbuffer({shape: [1, 1],
format: 'rgb5 a1'
})
console.log('renderbuffer: ', r.width, r.height, r.format)
```

Cube map and render buffer add properties

---

API.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mikolalysenko/regl/302)

Fix typo in API docs (comma vs colon)

---

lib/texture.js

Fixes so that we are correctly reporting an error if you use the texture types 'uint16', 'uint32', or 'depth stencil' without the 'WEBGL_depth_texture' extension.
This resolves issue #318.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/320)

Fix error message when using depth texture without extension.

---

lib/shader.js
test/stats.js

Fix so that `regl.stats.shaderCount` takes the shader cache into account.
This fixes issue #344.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/348)

shaderCount now takes the shader cache into account

---

lib/webgl.js

Hi – thanks for this project, really excited to start learning it. Just ran into a small problem – if you initialise with a non-canvas, non-body element, resizing fails because the height is calculated as `bounds.top - bounds.bottom` which is negative and therefore invalid.
Wasn't sure where to put a test for this, but if you need one am happy to update the PR if you point me in the right direction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/356)

fix resize of canvas in non-body element

---

API.md
CHANGES.md
lib/framebuffer.js
lib/read.js
regl.js
test/clear-fbo.js

This PR makes the APIs for working with framebuffers a bit more convenient.  It adds the following convenience methods:
* You can now bind framebuffers directly by calling `framebuffer.bind()` and passing in a function.  This saves you from having to write out a separate command for setting the framebuffer.
* `regl.clear` and `regl.read` now accept framebuffers as parameters.  This was a common point of confusion for many beginners who did not realize that you could access the framebuffer using a command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/362)

Improve ergonomics around framebuffers

---

example/cube-fbo.js

This pull request fixed two issues with the cubemap framebuffer example:
- In glsl `reflect(I, N)` should take an incident vector that is opposite to the
eyeDir (so -eyeDir) and a surface normal
More https://www.opengl.org/sdk/docs/man4/html/reflect.xhtml
- Cubemap was rendered upside down because FBO 0,0 is at the bottom left while for cubemaps 0,0 at the top left. The solution is to flip the UP vector in our lookAt matrix while rendering to the FBO. More here http://www.nvidia.com/object/cube_map_ogl_tutorial.html and here http://www.mbroecker.com/project_dynamic_cubemaps.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/368)

Fix example cube fbo

---

API.md
CHANGES.md
lib/framebuffer.js
test/clear-fbo.js

As pointed out by @vorg using bind for a property hanging off a function is a pretty bad idea.
This fixes that problem by renaming the new `bind()` helper method to `use()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/366)

rename framebuffer bind to use to avoid conflict

---

API.md

The syntax for arrays took me a bit to figure out and I'm still not 100% sure whether or not there's a more compact way (`colors: [[0, 1, 0, 1], [0, 0, 1, 1]]`?) This PR adds another uniform example to help communicate what's possible.
See: http://codepen.io/rsreusser/pen/ENqwoj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/389)

Add a couple more lines on passing array uniforms

---

browserify/transform.js

Previously, the file check in the browserify transform failed, resulting in large bundle sizes:
```
$ browserify -r regl | wc -c
272977
```
With this patch, the file sizes are back down to expected levels:
```
$ browserify -r regl | wc -c
75258
```
and with `--debug` you get the debugging symbols:
```
$ browserify --debug -r regl | wc -c
713677
$ browserify --debug -r regl | grep assert | wc -l
38
~ $ browserify -r regl | grep assert | wc -l
0
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/402)

check the main field in the transform comparison

---

API.md
dist/regl.d.ts
example/typescript/basic.ts
example/typescript/batch.ts
example/typescript/bunny.ts
example/typescript/camera.ts
example/typescript/dds.ts
example/typescript/dependencies.d.ts
example/typescript/dynamic.ts
example/typescript/elements.ts
example/typescript/envmap.ts
example/typescript/feedback.ts
example/typescript/geomorph.ts
example/typescript/life.ts
example/typescript/lighting.ts
example/typescript/mipmap.ts
example/typescript/particles.ts
example/typescript/scope.ts
example/typescript/text.ts
example/typescript/texture.ts
example/typescript/theta360.ts
example/typescript/tile.ts
example/typescript/video.ts
example/util/camera.d.ts
lib/stats.js
package.json
regl.d.ts
tsconfig.json

This PR resolves #238.
In addition to adding a type declaration file, `regl.d.ts`, I've ported some of the code examples (those that appear in http://regl.party/examples) to TypeScript, to demonstrate how the types could be used. I also made some updates to the API docs based on my research into the functionality of the library. I'm interested in @stevebest's work generating documentation from the type declaration file, but I haven't implemented that here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/457)

Typescript declarations

---

lib/framebuffer.js
test/framebuffer-simple.js

Add support of rgb format for fbo texture, which is not supported now, as below:
```js
const texture = regl.texture({
width, height,
format : 'rgb' // only support rgba now
});
const fbo = regl.framebuffer({
color : texture,
depth : true
});
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/476)

add support of rgb format for fbo texture

---

lib/util/check.js

The shader debugger which picks up base64 encoded shader names is encoding (btoa) instead of decoding (atob) the name string. Trivial fix.
(**a**scii-**to**-**b**inary)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/477)

Fix SHADER_NAME_B64 decoding Base64

---

test/util/browser.js

fix a typo failing `test-browser`

fix npm run test-browser

---

API.md
lib/texture.js

Supporting ImageBitmaps allows performant transfers of multiple large
textures. Textures will transfer synchronously (over texImage2D),
and converting some or all to bitmaps asynchronously before transferring
will reduce transfer time.
This PR adds support in lib/texture.js, and documents it in API.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/470)

Add support for ImageBitmap

---

test/framebuffer-parse.js

As mentioned in #479, there's a safari-specific half float bug that brings tests to a halt. Rather than a new failure, I believe this is instead the result of a new check for behavior that *does* seem broken in safari: https://github.com/regl-project/regl/commit/75730b6098985260438c16afc6d9a933bc7f9f2c#diff-6d2e0d9813eb0b2330521d6a391021d3R169
This PR doesn't fix anything (Babylon, for one, just [detects safari and reverts from half_float to float](https://github.com/BabylonJS/Babylon.js/pull/2509), I believe) but instead triggers a test failure that doesn't halt all tests.
In particular, it just wraps the test in a try/catch and reports a failure if it catches anything.

Report a safari-specific test failure without halting all tests

---

lib/core.js

While debugging code generation output, I noticed a subtle off-by-one error that probably doesn't have much of an effect, but which seems incorrect nonetheless:
The issue is that `>=` should instead be `>`. The incorrect version passes `undefined` to `vertexAttrib4f` instead of the zero fallback—though it maybe *does* actually use a zero fallback internally anyway.
To unpack that, `[1]` has length 1. The second conditional passes and causes the first *two* entries to use the array-specified value, which is incorrect since the second entry is then undefined.

Fix vertexAttrib4f constant length conditional

---

lib/util/pool.js

This code in `lib/util/pool.js`:
```javascript
module.exports = createPool()
// zero pool for initial zero data
module.exports.zero = createPool()
```
gets bundled by rollup as:
```javascript
var pool = createPool();
// zero pool for initial zero data
module.exports.zero = createPool();
```
As a result, `pool.zero` is undefined. At its core this seems like a rollup "bug" that results from the flat namespace not unpacking properties added to exports after the fact. This PR assigns `pool` to a variable, than adds `zero`, *then* exports.
The rollup'd output is:
```javascript
var pool = createPool();
// zero pool for initial zero data
pool.zero = createPool();
```
(though I have *not* rebuilt `dist/` as part of this PR.)
I checked and don't see any other occurrences of this in the codebase. …

Fix exports in pool

---

lib/framebuffer.js

The case where the next framebuffer is not the drawing buffer wasn't handled correctly.

Fix a bug with framebuffer binding not working recursively in contexts

---

lib/util/check.js

Error logs don't work on chrome which is extremely annoying.  Will keep this turned off until they get fixed.

Disable logging styles for error reporting in chrome

---

regl.d.ts

This PR corrects the signature of the function `Texture2D.subimage`. Optional args `x`, `y`, and `level` can be provided whether the first argument is `TextureImageData` or `Texture2DOptions`. Verified that this works at runtime.

Fix type def TextureImage2D.subimage overload.

---

API.md

x,y in `regl.read` should be offset from **lower-left** instead of current upper-left.
reference: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels

fix description of x,y in doc of regl.read()

---

example/point-light-shadow.js

The sampled shadow visibility should be multiplied by diffuse, not ambient.

Fix point light shadow example

---

API.md

Taken from chat at: https://gitter.im/mikolalysenko/regl?at=5c07423f28907a3c7bccc3e9
Let me know if there's more to expand on 
my editor removed trailing whitespace

Add note about regl.draw()  to documentation

---

dist/regl.d.ts
regl.d.ts

Fix types in FramebufferCube.
This fix the error `Property 'faces' does not exist on type 'FramebufferCube'` when try to port to Typescript the example `point-light-shadow`. See [Line 142](https://github.com/regl-project/regl/blob/e36bef9379b63918514c7fa7d2e5abf413634f56/example/point-light-shadow.js#L142).

Fix types framebuffercube

---

lib/core.js
test/attribute-constants.js
test/util/create-context.js

This PR fixes switching between constant and non-constant attributes. See: #474. At the end of the day, the simple problem was that constant attributes set some properties on the `BINDING` via
```js
CUTE_COMPONENTS.map(function (c, i) { 
return BINDING + '.' + c + '=' + CONST_COMPONENTS[i] + ';'
}).join(''),
```
but do not actively *unset* `buffer`. As a result, the the next call to a buffer attribute does not notice that buffer attributes were previously disabled and now must be enabled. The solution was to simply set `BINDING.buffer=null` when using constant attributes.
The other half of the debugging was working around a strange instanced arrays interaction detailed in #544.
Sorry it took so long to get to to the bottom of this, but thanks @dy for providing such a debuggable test case!

Fix switching between const and non-const attributes

---

lib/texture.js
test/texture2d.js

This PR is a fix to depth texture's initialization, e.g:
```js
regl.texture({
format: 'depth',
type: 'uint32'
})
```
When calling `gl.texImage2D` with depth texture, the last param `data` can't be an allocated array, otherwise the following webgl error will be thrown out:
`WebGL: INVALID_OPERATION: texImage2D: format can not be set, only rendered to`
```js
//with depth texture, data must be null
gl.texImage2D(target, miplevel, format, width, height, 0, format, type, data)
```
[reproduction](https://codepen.io/fuzhenn-the-decoder/pen/vYBvEwv): The webgl error will be printed out in console.

fix texImage2D with depth texture

---

lib/texture.js

Without this change, even when texture options have `format == "srgb"`, it would use `GL_RGB` anyways.

Support sRGB texture format

---

lib/attribute.js
lib/core.js
test/vao.js

Fix a parsing bug where the resource type of a static vertex array object was not being correctly determined.

Fix static VAO resources

---

example/dynamic-resize.js
lib/webgl.js

Use `ResizeObserver` when available to detect changes in canvas container size, except if rendering full screen (to body).

Resize canvas using ResizeObserver if available

---

README.md

I recently switched my web-based interactive electromagnetic field simulation to use regl which was very easy to do (took me only a day). Thank you for the great library!
The live version can be found here: https://cemsim.com
And the repository here: https://github.com/RobinKa/maxwell-simulation

Add cemsim.com (EM sim) to projects

---

lib/attribute.js

@rreusser FYI - on `plotly.js` repo we had problem upgrading because of those es6 keywords.

Fix to continue support es5

---

lib/webgl.js

See #565 
It seems to be the case that a browser was behaving buggily with no premultipliedAlpha value specified so that regl elects to fill it in. However, the false value supplied by regl seems to conflict with the preferred value in [WebGLContextAttributes which appears to be true](https://www.khronos.org/registry/webgl/specs/1.0/#5.2):
```
dictionary WebGLContextAttributes {
...
GLboolean premultipliedAlpha = true;
};
```
If merged, this will be published as a minor version under 1.6.0.
/cc @mikolalysenko @dy @archmoj

Fix a non-standard default value for premultiplied alpha

---

lib/attribute.js

Includes the following fixes and improvements:
* destroy vao.buffers in `vao.destroy()`
* not call `vertexAttribDivisorANGLE` if divisor is 0
* when updating vao, call `buffer.subdata` instead of creating a new buffer every time
* add support of data object when creating vao:
```js
regl.vao([
// data object to support in this PR
{ data: new Float32Array(8), usage: 'dynamic' },
// now we only support array
Float32Array(32)
])
```

some vao fixes

---

lib/core.js
lib/dynamic.js
regl.d.ts
regl.js
test/uniforms.js

This PR adds support for prop vector uniforms.  It simplifies integrating with libraries that may not use array-like vector components.  For example, you can now write:
```javascript
regl({
// ...
uniform: {
color: [ regl.prop('r'), regl.prop('g'), regl.prop('b'), regl.prop('a') ]
},
})
```
Instead of:
```javascript
regl({
// ...
uniform: {
color: (context, props) => [ props.r, props.g, props.b, props.a ],
},
})
```
While this may seem more verbose, it allows you to avoid creating an extra array reference and thus reduce memory allocations.

Add support for prop vectors in uniforms and context

---

API.md
lib/attribute.js
lib/core.js
lib/util/codegen.js
regl.d.ts
regl.js
test/vao-elements.js

This PR fixes how vertex array object elements work.  The previous interface was based on my own (wrong) understanding of the VAO spec.  I didn't realize that a vertex array object binding included the element buffer state... (dumb)
So the old interfaces didn't reflect the underlying reality and needed to change.  As a result I've made this patch which is the first breaking change in regl.
Most programs should continue to work without modification, but if you are using vertex array objects with elements you will need to move the element state into your VAO definition or else it will break.
All other regl programs should continue to work as usual.

Fix VAO elements

---

example/point-light-shadow.js

Ensure the depth map is cleared between generating the different faces of the cubemap. If this isnt done, only the first face will have accurate values.

Fix depth write failure on shadow cubemap generation

---

lib/core.js
lib/shader.js
test/browser.js
test/uniform-array.js

Fix #258 
* Simpler way to set array type uniform values
* use [uniform[1234][fi]v](https://developer.mozilla.org/zh-CN/docs/Web/API/WebGLRenderingContext/getUniform) instead to produce far less webgl commands
* glsl
```glsl
uniform vec4 lights[3];
```
* regl config
```js
{
vert,
frag,
uniforms: {
// // old ways is still backward supported
// 'lights[0]': [1, 0, 0, 1],
// 'lights[1]': [0, 1, 0, 1],
// 'lights[2]': [0, 0, 1, 1],
// flatten vectors same as gl.uniform4fv required
lights: [1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1]
}
}
```

Simpler way to set array type uniform values

---

example/dynamic-resize.js
lib/webgl.js

Fixes #563 
There was a problem with canvas' `resize()`: canvas is set to a resolution (and size) equal to `getBoundingClientRect` of the parent. This introduces feedback loop effects every time `resize()` is triggered. Instead of bounding box, it should be set to the size of content box.
Solution is as follows: set `width` and `height` of the canvas to `100%` so that it always fills the parent's content box. Update **only** canvas' resolution to be equal to the `getBoundingClientRect` of itself. This way we avoid any feedback loops that can arise, since changing the resolution does not influence canvas' (and in turn, parent's) size.

Fix canvas resizing behavior

---

lib/attribute.js

Found this bug when porting 2.0.1, when refreshing multiple VAO, an elements buffer is binded to a wrong VAO object.
Reset vao status in vao.bindAttrs will fix it.

fix wrong binding when refreshing multiple vaos

---

lib/core.js

In some cases, users need to have more control on elements with VAO.
* problem as #589 
* when elements needs to be updated frequently (icon fading etc)
Allowing to specify elements along with VAO can fix the above problems, and won't break webgl spec either.

allow to specify elements with VAO, fix #589

---

example/elements.js
example/graph.js
example/line-primitives.js

Used Math.max to simplify the lineWidth logic in elements example. The if statement was a little harder to follow, using Math.max makes it easier to figure out what's going on at a glance and reduces code size.

Simplify Elements example by using Math.max

---

API.md

Resolves #634 
Attributes get their type from the buffer. However, if you interleave multiple data types into a single buffer, you may wish to specify different types for different attr uses of the same buffer. Regl attributes support `type` in order to accomplish this, though the docs don't mention it.
For a working example, see: https://observablehq.com/d/3c5584380a5a42a4

Add missing parameter to attribute opts

---

README.md

Hey there, we're using `regl` at the Allen Institute to build a scalable data visualization tool for our scientists and we wanted to add it to the list of projects to show off what `regl` can do!

Add Allen Institute ABC Atlas to projects list

---

CHANGES.md
package-lock.json
package.json

This is just a tiny patch release with no that tries to dust off the cobwebs and keep the wheels turning a bit longer by making maintenance perhaps a bit easier. It contains #676, #675, and #674.
Side note: I tried bulk-updating all of the deps, but there was nothing to be gained from it. Except about 1 additional kb to the minified bundle size for random reasons that only google closure knows.

Version 2.1.1
