lib/buffer.js
test/subdata.js

This fixes the bug in https://github.com/mikolalysenko/regl/issues/23

Support arrays of typedarrays in buffers

---

API.md
CHANGES.md
README.md
example/audio.js
example/batch.js
example/bunny.js
example/camera.js
example/cloth.js
example/dds.js
example/dynamic.js
example/envmap.js
example/feedback.js
example/geomorph.js
example/life.js
example/lighting.js
example/microphone.js
example/mipmap.js
example/particles.js
example/text.js
example/theta360.js
regl.js

This PR changes the `count` context variable to the shorter and more descriptive `tick`.  A bunch of demos and code will break with this, but it is better to get this over with sooner than later.

Rename count to tick

---

example/cloth.js

now that the delta is constant, the wind in the cloth example was less noticeable. So I made the wind stronger, so that it is more noticeable.

made cloth wind stronger

---

CHANGES.md

Add "pretty printer for the generated code" to the list of planned stuff

Add "pretty printer" to "Planned"

---

package.json

Added a description to `package.json`

Added a description to `package.json`

---

regl.js

Add null-check for `timer` to `updateTimer()`

Add null-check for `timer` to `updateTimer()`

---

README.md

README.md: fix broken benchmarking results link

README.md: fix broken benchmarking results link

---

test/texture2d.js

Add TODO that says that we should also add test case for 'mipmapHint'

test/texture2d.js: add 'test mipmapHint' TODO

---

API.md

API.md: Fix gl.LINES single quotes

---

API.md
lib/texture.js

Cube resize tweak

---

lib/buffer.js
lib/core.js
lib/util/codegen.js

Clear stream buffer pool on regl.destroy()

---

bench/draw-stream.js
bench/list.js
www/bench.html

Add benchmark that profiles stream buffers.
This benchmark should prevent issue #109 from popping up unnoticed again.

Add bench/draw-stream.js: Add benchmark that profiles stream buffers.

---

lib/dynamic.js

This PR throws away unused code from `lib/dynamic.js`. All test cases still pass.

Simplify lib/dynamic.js

---

API.md

Fix some things in framebuffer docs.

framebuffer docs fixes

---

example/cube-fbo.js

Cleaned up a bit, and added comments.

Clean up `example/cube-fbo.js`

---

API.md

Fix the descriptions of the renderbuffer floating point formats.

API.md: fix framebuffer color format table.

---

lib/framebuffer.js

lib/framebuffer.js: Add FIXME to FramebufferCube, for sections that need to be looked over.

lib/framebuffer.js: Add FIXME to FramebufferCube,

---

test/textureCube.js

test/textureCube.js: fix test

---

test/projection.js
test/util/index.js

Working toward solving https://github.com/mikolalysenko/regl/issues/79

Add a unit test for pixel coordinate projections

---

test/projection-lines.js
test/util/index.js

More viewport rounding debug stuff

Line projection test

---

README.md
compare/threejs_cube.html

Normalize the threejs demo so that the camera moves the same as the other demos.

Normalize the threejs demo

---

README.md

Small documentation tweak, adds a link to npm cdn.

Fix cdn links

---

lib/extension.js

This PR removes some unused cruft from the extension submodule and gets the code coverage for lib/extension.js to 100%.

Remove unused code paths from lib/extension.js

---

README.md

Switch gallery link to https. Otherwise, the microphone example can't be run.

Switch gallery link to https

---

example/planar-reflection.js

example/planar-reflection.js: Made the planar reflection more visible

example/planar-reflection.js: Made the planar reflection more visible

---

lib/core.js
lib/util/check.js

Fix shader error message logs

---

example/line.js

Demonstrates screen space projected lines (from technique described in https://mattdesl.svbtle.com/drawing-lines-is-hard) and offset buffer attributes.
cc @mattdesl

Add line mesh example

---

README.md

Add project list

---

test/sample.js

Partially solves issue #208, by adding testing for dynamic nested properties for sample coverage.

Sample Coverage: Add test cases for nested dynamic properties.

---

test/polygon-offset.js

Add test cases for dynamic nested properties.

---

README.md

Add "helped wanted" section to README.

README.md: Add "helped wanted" section.

---

example/camera.js
example/util/camera.js

Just pushing because I keep getting distracted.  This revamps the previous camera code to use a new utility module for camera code.
There are a few rough edges but it is way less boilerplate than before, and because it is in the same repo we can start iterating on it quickly.
I'll make a PR later to add some docs, but got to catch a plane.

New camera module

---

README.md

New header courtesy of @yoshuawuyts

New header

---

README.md

This PR adds some header links to the README for various sections.

Add header links

---

API.md
CHANGES.md
lib/buffer.js
lib/core.js
lib/elements.js
lib/extension.js
lib/framebuffer.js
lib/renderbuffer.js
lib/shader.js
lib/texture.js
lib/timer.js
lib/util/check.js
regl.js
test/context-loss.js
test/util/index.js

This is a first pass at context loss handling in `regl`.  It implements recovery for static resources and reinitializes dynamic resources.  User are responsible for reinitializes textures and dynamic buffers.
Closes #8

Context loss handling

---

CHANGES.md
lib/core.js
test/attributes.js

Attribute pointers can now take buffer literals

---

lib/core.js

Fix error reporting for static gl properties

---

README.md

Add regl-cnn to list of projects using regl.

README.md: regl-cnn to list of project

---

API.md

Write docs for the 'type' option of `regl.elements`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mikolalysenko/regl/293)

API.md: document 'type' for regl.elements

---

API.md

Write docs for the `type` option of `regl.buffer`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mikolalysenko/regl/294)

API.md: docs for regl.buffer type

---

lib/texture.js

Remove some remainders from the texture rewrite of last month.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mikolalysenko/regl/298)

lib/texture.js: Remove remainder from texture rewrite

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/310)

Fix circle ci badge

---

README.md

Fix links that were broken with the org creation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/309)

README.md: Fix broken links.

---

API.md

Fix the wording for "buffer subdata" section.
Fixes issue #321.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/322)

API.md: Fix subdata wording.

---

lib/framebuffer.js
test/framebuffer-depth-stencil.js

Fixes #319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/334)

Depth texture

---

API.md

fix little typo 🐌
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/347)

fix description of data types

---

API.md

stumbled across this while reading the docs. 
Awesome work! Thanks a lot <3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/352)

add missing quotes in API.md

---

API.md
README.md

This hopefully should help clear up some of the confusion caused by #361
It adds some additional documentation around `--debug` and browserify.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/363)

Update docs around error messages

---

README.md

a screenshot from npmjs:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/365)

seems npm cannot read capital letters in readme

---

API.md
lib/util/check.js
test/texture2d.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/367)

Changed texture alignment to refer to row rather than pixel alignment.

---

bin/build-gallery.js

~This PR allows for targeted builds of gallery components~. It ensures gallery components are only built when changed or if the target file does not exist. This functionality is possible by checking the `mtime` stat on a file. This is very similar to how `Makefile` target dependencies work
cc @mikolalysenko @Erkaman @substack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/384)

build based on mtime

---

lib/core.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/387)

Fix typo on error message

---

API.md

Updates the image texture load example to indicate that it is an async operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/403)

Update Image texture example to async

---

lib/texture.js

Fixes #441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/442)

Use default color space for mipmap

---

example/shadow-volume.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/439)

Fix GPU Gems url

---

API.md

Fixes #436
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/449)

finish props section

---

test/attribute-constants.js

This adds a few more test cases for attribute constants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/450)

Dynamic attribute constant tests

---

API.md

Fix #391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/451)

Fix up blending mode docs

---

README.md

Over the past couple months I've put out a couple projects using regl, so I figured I'd add them to the list!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/473)

Add a couple example projects using regl

---

lib/texture.js
test/textureCube.js

Details refers to #471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/472)

fix conflicts of cube texture's faces and min filter, close #471

---

example/texture.js
example/video.js

The image/video have both been rendered horizontally flipped. Not sure if anyone noticed?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/regl-project/regl/466)

Unflip baboon and the poor doggo

---

lib/framebuffer.js

Fix linting error that was causing Travis build to fail

---

README.md

As reported in https://github.com/regl-project/regl/issues/493
The new chat link is the one mentioned in the issue and looks correct to me but I'm new to Regl so feel free to correct or close the PR

Point chat link at working chat

---

lib/texture.js

feat(texture.js): Adds OffscreenCanvas type for use in a WebWorker

---

DEVELOPING.md

Simply updated the example script to search for the file within `example` folder.
@rreusser

use example folder in dev script

---

lib/shader.js

@rreusser here is one more fix needed for es5.
I appreciate if you could posibly release 1.5.2.

One more fix to continue with es5

---

lib/webgl.js

allow context to disable premultipliedAlpha when set to false

---

README.md

Hi there! We have been using regl in the newest version of our app Repper. I am very happy I found regl because it fits a lot better in my declarative approach to interface building, and combining it with React works great! I hope you will add our project as an example of a commercial project built with regl.

Repper app as example project

---

lib/texture.js
regl.js

Fix texture refresh behavior

---

lib/dynamic.js

Fix for es5 users.
@rreusser 
@mikolalysenko

fix - rewrite using es5

---

lib/core.js
lib/framebuffer.js
lib/read.js
lib/texture.js

This PR modifies batch mode to only emit uniform calls in the inner loop if the values actually change.  This can give a small speed up in some cases.

Small optimization for batch mode

---

README.md

Started using REGL with this project. Great library, perfect balance of complexity / freedom, thank you for creating this!

Added Synesthesia to Projects

---

README.md

[Fractal.garden](https://fractal.garden) is an interactive 3d fractal explorer. Regl has been super helpful for this.

Added fractal.garden to list of projects using regl

---

README.md

We started using ReGL earlier this year

Add Bokeh to list of projects using

---

example/video.js

fix: https://github.com/regl-project/regl/issues/469

fix: chrome video don't show  bug

---

README.md

Innovative project (I'm biased) under active development.

Add Deepscatter in projects list

---

regl.d.ts

I'm having some issues passing textures to the command when using typescript. This seems to alleviate that issue.

[TS] Add Texture to Uniform type
